### ISSUE TITLE
Powershell Throws error during "Find change author & commit the backup" section

### ISSUE THREAD

**Issue by KYTON06** [ztrhgf/DevOps_Pipelines#1]
![image](https://github.com/ztrhgf/DevOps_Pipelines/assets/65706619/a1180236-9c01-4b3a-8cb1-7c10b1c57625)

Error thrown during the Find change author & commit the backup section,

Script appears to be finding all the historical changes but cant seem to commit them to a file.

Any Help is appreciated.

**Comment by KYTON06** [comment]
Please Ignore request, I figured it out almost immediately after posting this.

You are unable to have Quotation marks (") in the name of your Remediations in Intune, this breaks the Script logic and it fails.

**Comment by ztrhgf** [comment]
We are talking about this part I guess? 
![image](https://github.com/ztrhgf/DevOps_Pipelines/assets/2930419/fec9e1b0-a834-48dc-9cc3-db3c41fa10d2)

So some sort of escaping quotation marks would solve this issue as well...

**Comment by KYTON06** [comment]
Yeah, for now I have just renamed the Remediation and it has resolved the problem.

Long term could be fixed with Escaping Quotation Marks, or some other logic for name parsing.
