### ISSUE TITLE
Markdown Export to PDF failing

### ISSUE THREAD

**Issue by KYTON06** [ztrhgf/DevOps_Pipelines#2]
Hi,

Wondering if you have seen the below before, the Markdown to PDF conversion is failing because it cant find the files its looking for.
I've just decided to enable this feature and I cant get it to work as expected.
![image](https://github.com/ztrhgf/DevOps_Pipelines/assets/65706619/24569cfd-dbce-4dec-ae86-cfdd93fbfefe)

Any help is appreciated.

Thanks

**Comment by ztrhgf** [comment]
I was missing this part in the original post. It's fixed now.

Check https://doitpsway.com/how-to-easily-backup-your-intune-environment-using-intunecd-and-azure-devops-pipeline#heading-what-does-this-pipeline-do 

This part 👇![image](https://github.com/ztrhgf/DevOps_Pipelines/assets/2930419/6f64066c-7910-43b3-a492-a5d3e6ddddcd)
