### ISSUE TITLE
Fails on backup_remoteAssistancePartner.py

### ISSUE THREAD

**Issue by Kofl** [ztrhgf/DevOps_Pipelines#3]
Hi,

awesome tool, thanks a lot.

Failed for us first. Probably because we had in the past Teamviewer integrated.
A new exclude fixed it, didnt find a GRAPH API permission for it so far.

```

            IntuneCD-startbackup \
                --mode=1 \
                --output=json \
                --path="$(Build.SourcesDirectory)/$(BACKUP_FOLDER)" \
                --exclude CompliancePartner RemoteAssistancePartner \
                --append-id
```

> Traceback (most recent call last):
>   File "/home/vsts/.local/bin/IntuneCD-startbackup", line 8, in <module>
>     sys.exit(start())
>   File "/home/vsts/.local/lib/python3.10/site-packages/IntuneCD/run_backup.py", line 271, in start
>     run_backup(
>   File "/home/vsts/.local/lib/python3.10/site-packages/IntuneCD/run_backup.py", line 218, in run_backup
>     backup_intune(results, path, output, exclude, token, prefix, append_id, args)
>   File "/home/vsts/.local/lib/python3.10/site-packages/IntuneCD/backup_intune.py", line 118, in backup_intune
>     results.append(savebackup(path, output, token, append_id))
>   File "/home/vsts/.local/lib/python3.10/site-packages/IntuneCD/backup/Intune/backup_remoteAssistancePartner.py", line 29, in savebackup
>     data = makeapirequest(ENDPOINT, token)
>   File "/home/vsts/.local/lib/python3.10/site-packages/IntuneCD/intunecdlib/graph_request.py", line 85, in makeapirequest
>     raise requests.exceptions.HTTPError(
> requests.exceptions.HTTPError: Request failed with 403 - {"error":{"code":"Forbidden","message":"{\r\n  \"_version\": 3,\r\n  \"Message\": \"An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 449918c1-d88c-4dbe-a359-cdee03985fea - Url: https://fef.msub05.manage.microsoft.com/RemoteAssistService/StatelessRemoteAssistService/deviceManagement/remoteAssistancePartners?api-version=5022-08-15 - CustomApiErrorPhrase: Forbidden\",\r\n  \"CustomApiErrorPhrase\": \"Forbidden\",\r\n  \"RetryAfter\": null,\r\n  \"ErrorSourceService\": \"\",\r\n  \"HttpHeaders\": \"{}\"\r\n}","innerError":{"date":"2024-01-14T18:43:40","request-id":"449918c1-d88c-4dbe-a359-cdee03985fea","client-request-id":"449918c1-d88c-4dbe-a359-cdee03985fea"}}}
> 
> ##[error]Bash exited with code '1'.
> ##[error]Bash wrote one or more lines to the standard error stream.
> ##[error]Traceback (most recent call last):
>   File "/home/vsts/.local/bin/IntuneCD-startbackup", line 8, in <module>

**Comment by ztrhgf** [comment]
Sorry for late response. I would try to contact IntuneCD owner directly https://github.com/almenscorner/IntuneCD/issues
